# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='text',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
