# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 22:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionpost',
            name='downvotes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.downvoteQuestionPost'),
        ),
        migrations.AlterField(
            model_name='questionpost',
            name='upvotes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.upvoteQuestionPost'),
        ),
    ]
