# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 15:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_questionpage_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=128, unique=True)),
                ('upvotes', models.IntegerField(default=0)),
                ('downvotes', models.IntegerField(default=0)),
                ('text_field', models.CharField(max_length=10000)),
                ('slug', models.SlugField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Category',
            new_name='Faculty',
        ),
        migrations.RemoveField(
            model_name='question',
            name='category',
        ),
        migrations.AlterModelOptions(
            name='faculty',
            options={'verbose_name_plural': 'Faculties'},
        ),
        migrations.AddField(
            model_name='questionpage',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questionpage',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='questionpage',
            name='title',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='questionpage',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.QuestionPost'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, upload_to='profile_images'),
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.AddField(
            model_name='school',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.Faculty'),
        ),
        migrations.AddField(
            model_name='questionpost',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.QuestionPage'),
        ),
        migrations.AddField(
            model_name='module',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.School'),
        ),
        migrations.AddField(
            model_name='questionpage',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.Module'),
        ),
    ]
