# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20170323_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downvotequestionpost',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
