# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 15:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20170307_1530'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Faculty',
            new_name='College',
        ),
        migrations.AlterModelOptions(
            name='college',
            options={},
        ),
        migrations.RenameField(
            model_name='school',
            old_name='faculty',
            new_name='college',
        ),
    ]
