# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20170324_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionpost',
            name='pid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='questionpost',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
