# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 20:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_auto_20170309_1947'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='college',
            options={'verbose_name_plural': 'Colleges'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'verbose_name_plural': 'Modules'},
        ),
        migrations.AlterModelOptions(
            name='questionpage',
            options={'verbose_name_plural': 'QuestionPages'},
        ),
        migrations.AlterModelOptions(
            name='questionpost',
            options={'verbose_name_plural': 'QuestionPosts'},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'verbose_name_plural': 'Schools'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name_plural': 'UserProfiles'},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='category',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='title',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='views',
        ),
        migrations.RemoveField(
            model_name='questionpost',
            name='title',
        ),
        migrations.AddField(
            model_name='college',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default=b'', on_delete=django.db.models.deletion.CASCADE, to='forum.QuestionPost'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.UserProfile'),
        ),
        migrations.AddField(
            model_name='module',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='questionpost',
            name='slug',
            field=models.SlugField(default=b'', unique=True),
        ),
        migrations.AddField(
            model_name='school',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='questionpage',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='questionpage',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='questionpage',
            name='title',
            field=models.CharField(default=b'untitled', max_length=128, unique=True),
        ),
    ]
