# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 20:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_auto_20170318_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionpost',
            name='slug',
        ),
    ]
